---
title: "Réglage modèles"
author: "tlm"
date: "14/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(modelr)
library(randomForest)
```

## Chargement des données
```{r message=FALSE, results='hide'}
source("miseenformedonnees.R")
```
## Traitement des données

```{r}
lanfish = lanquant.co[c(8:157)]
disfish = disquant.co[c(8:157)]
colnames(lanfish) = paste0("X",c(1:150))
colnames(disfish) = paste0("Y",c(1:150))
lanzeros = which(colSums(lanfish)!=0)
diszeros = which(colSums(disfish)!=0)
lanfish = subset(lanfish, select=c(lanzeros))
disfish = subset(disfish, select=c(diszeros))

lanfish$month = lanquant.co$month
lanfish$rect = lanquant.co$rect

xnames = colnames(lanfish)
ynames = colnames(disfish)
strsumx = paste(xnames, collapse= "+")

data = data.frame(lanfish,disfish)
```

## Données d'entraînement et de test

```{r}
#Build train and test sets
set.seed(55)
proportion = 0.7
train_ind = sample(seq_len(nrow(data)), size = floor(proportion * nrow(data)))
train = data[train_ind, ]
test = data[-train_ind, ]
```
## Réglage random forests
```{r warning=FALSE}
nlist = 5^(1:3)
mlist = seq(10, length(xnames), 20)
grid = expand.grid(ntree=nlist,mtry=mlist)
print(grid)
res = data.frame(matrix(ncol = length(ynames), nrow = dim(grid)[1]))
colnames(res) = ynames
for (yname in ynames) {
  fmla = as.formula(paste0(yname, "~", strsumx))
  for (k in c(1:dim(grid)[1])) {
    rf_mod <- randomForest(fmla, data=train, ntree=grid$ntree[k], mtry=grid$mtry[k])
    res[k, yname] = rmse(rf_mod, test)
  }
}
res
```